---
title: "DGAEP Simulator"
author: "Pedro Mariano"
date: "2024-07-23"
classoption:
  - t
  - aspectratio=169
output: beamer_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## DGAEP Dataset

* Excel spreadsheet with
  * information about public jobs
  * organised by semester, by administration, by ministry and secretariat, by age group, by sex, by number of jobs \ldots
  
* Dataset was preprocessed to create a table

| timestamp | administration | ministry_secretariat | age_group | sex | number_jobs |
|----------:|:---------------|:---------------------|----------:|:----|-------------:|
| 2011.5 | Administração Central  | Educação  | 5 |   H     |           176 |
| 2011.5 | Administração Central  | Educação | 5 | M | 672 |
| \vdots |                        |          |   |   |     |

## Simulation Model

* We can compute the variation in the number of jobs
  * in a given time period
  * for a particular combination of administration, ministry and secretariat
* Problems with data about job post transfer
  * different reporting methods
  * data omissions
* If we have a model of the job variation, $\mathcal{D}_{c,a,g}$
  * we can compute a time series
  
  
## Job Variation Model

* Number of jobs in the data set is represented by

  $p_{c,a,g}(t,f)$
  
  where
  
  * $c$ is the ministry and secretariat
  * $a$ is the administration
  * $g$ is the gender
  * $t$ is the time period
  * $f$ is the age group

$\mathcal{D}_{c,a,g}(T) = \{x: x=p_{c,a,g}(t+T,f)-p_{c,a,g}(t,f) \}$

* Does not take into account ageing explicitly
  * during the elapsed time $T$ some people in age group $f$ get older and pass to age group $f+1$
* The difference considers job promotions, new hirings, firings, getting old

...